name: doxy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: sudo apt-get install ninja-build doxygen graphviz mscgen dia
      - name: Configure
        run: cmake -G Ninja -B ${{runner.temp}}
      - name: Build, test and document
        working-directory: ${{runner.temp}}
        run: |
          ninja doxy
      # https://github.com/JamesIves/github-pages-deploy-action
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{runner.temp}}/html
